ARG NODE_VERSION=26-alpine

FROM node:${NODE_VERSION} AS base
WORKDIR /app

FROM base
COPY . .

COPY package.json . package-lock.json* ./
RUN npm install

EXPOSE 5173
EXPOSE 24678

CMD ["npm", "run", "dev"]
