services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/pb/pb_data:/pb/pb_data
      - ./backend/pb/pb_migrations:/pb/pb_migrations
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
          ignore:
            - node_modules/
            - .svelte-kit/
            - build/
    depends_on:
      - backend

volumes:
  pb_data:
