services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile

  backend:
    image: ghcr.io/mattismoel/portfolio/backend:main
    volumes:
      - pb_data:/pb/pb_data
      - pb_migrations:/pb/pb_migrations

  frontend:
    image: ghcr.io/mattismoel/portfolio/frontend:main
    restart: unless-stopped
    environment:
      - PUBLIC_POCKETBASE_URL=$PUBLIC_POCKETBASE_URL
      - POCKETBASE_URL=$POCKETBASE_URL

volumes:
  caddy_data:
  caddy_config:
  pb_data:
  pb_migrations:

configs:
  caddyfile:
    file: ./Caddyfile
