name: Publish Backend Image

on:
  pull_request:
    branches: ["main", "dev", "edge"]
    paths:
      - "backend/**"
      - ".github/**"
  push:
    branches: ["main", "dev", "edge"]
    paths:
      - "backend/**"
      - ".github/**"

jobs:
  publish-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Publish Backend
        uses: mattismoel/actions/deploy@main
        with:
          context: ./backend
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_name: backend
