name: Publish Web Server Image

on:
  pull_request:
    branches: ["main", "dev", "edge"]
    paths:
      - "frontend/**"
      - ".github/**"
  push:
    branches: ["main", "dev", "edge"]
    paths:
      - "frontend/**"
      - ".github/**"

jobs:
  publish-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Publish Frontend
        uses: mattismoel/actions/deploy@main
        with:
          context: ./frontend
          package_name: frontend
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            PUBLIC_POCKETBASE_URL=${{ secrets.PUBLIC_POCKETBASE_URL }}
            POCKETBASE_URL=${{ secrets.POCKETBASE_URL }}
