name: Publish Backend

env:
  REGISTRY: ghcr.io
  PACKAGE_NAME: backend

on:
  push:
    branches: ["main", "dev", "edge"]
    paths:
      - "backend/**"
      - ".github/**"

jobs:
  publish-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY}}/${{ github.actor }}/${{ github.event.repository.name }}/${{ env.PACKAGE_NAME }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
